<?php

declare(strict_types=1);

namespace SymPress\Orm\Dbal;

final class WpdbConnection implements ConnectionInterface
{
    private SqlPlatformInterface $platform;

    private int $transactionNesting = 0;

    public function __construct(
        private ?\wpdb $database = null,
        ?SqlPlatformInterface $platform = null,
    ) {

        $this->platform = $platform ?? new WordPressSqlPlatform();
    }

    public function platform(): SqlPlatformInterface
    {
        return $this->platform;
    }

    public function tablePrefix(): string
    {
        return $this->database()->prefix;
    }

    public function charsetCollate(): string
    {
        return $this->database()->get_charset_collate();
    }

    public function escapeLike(string $value): string
    {
        return $this->database()->esc_like($value);
    }

    public function prepare(string $sql, mixed ...$parameters): string
    {
        if ($parameters === []) {
            return $sql;
        }

        // SQL is generated by the ORM/query builder layer before it reaches this WordPress adapter.
        // @phpstan-ignore argument.type
        $prepared = $this->database()->prepare($sql, ...$parameters);

        if (!is_string($prepared)) {
            throw new \RuntimeException('Unable to prepare SQL statement.');
        }

        return $prepared;
    }

    public function fetchOne(string $sql, mixed ...$parameters): mixed
    {
        // @phpstan-ignore sympress.preparedSql (Trusted DBAL SQL contract: query builders validate identifiers and bind values through this adapter.)
        return $this->database()->get_var($this->prepare($sql, ...$parameters));
    }

    public function fetchAllAssociative(string $sql, mixed ...$parameters): array
    {
        /** @var list<array<string, mixed>> $rows */
        $rows = $this->database()->get_results($this->prepare($sql, ...$parameters), ARRAY_A); // @phpstan-ignore sympress.preparedSql (Trusted DBAL SQL contract, validating identifiers and binding values before execution.)

        return $rows;
    }

    public function insert(string $table, array $data): bool|int
    {
        return $this->database()->insert($table, $data);
    }

    public function update(string $table, array $data, array $criteria): bool|int
    {
        return $this->database()->update($table, $data, $criteria);
    }

    public function delete(string $table, array $criteria): bool|int
    {
        return $this->database()->delete($table, $criteria);
    }

    public function executeStatement(string $sql, mixed ...$parameters): bool|int
    {
        // @phpstan-ignore sympress.preparedSql (Explicit DBAL raw SQL contract, including schema DDL and transaction control; values use prepare.)
        return $this->database()->query($this->prepare($sql, ...$parameters));
    }

    public function lastInsertId(): int
    {
        return $this->database()->insert_id;
    }

    public function beginTransaction(): void
    {
        $sql = $this->transactionNesting === 0
            ? $this->platform->beginTransactionSql()
            : 'SAVEPOINT sympress_' . $this->transactionNesting;

        if ($this->executeStatement($sql) === false) {
            throw new \RuntimeException('Unable to begin transaction.');
        }

        $this->transactionNesting++;
    }

    public function commit(): void
    {
        if ($this->transactionNesting <= 0) {
            return;
        }

        $remaining = $this->transactionNesting - 1;

        $sql = $remaining === 0
            ? $this->platform->commitTransactionSql()
            : 'RELEASE SAVEPOINT sympress_' . $remaining;

        if ($this->executeStatement($sql) === false) {
            throw new \RuntimeException('Unable to commit transaction.');
        }

        $this->transactionNesting = $remaining;
    }

    public function rollBack(): void
    {
        if ($this->transactionNesting <= 0) {
            return;
        }

        $remaining = $this->transactionNesting - 1;
        $sql = $remaining === 0
            ? $this->platform->rollbackTransactionSql()
            : 'ROLLBACK TO SAVEPOINT sympress_' . $remaining;

        if ($this->executeStatement($sql) === false) {
            throw new \RuntimeException('Unable to roll back transaction.');
        }

        $this->transactionNesting = $remaining;
    }

    public function isTransactionActive(): bool
    {
        return $this->transactionNesting > 0;
    }

    private function database(): \wpdb
    {
        if ($this->database instanceof \wpdb) {
            return $this->database;
        }

        $database = $GLOBALS['wpdb'] ?? null;

        if ($database instanceof \wpdb) {
            return $this->database = $database;
        }

        throw new \RuntimeException('Global $wpdb is not available.');
    }
}
